# Generated by Django 4.1.3 on 2022-11-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_created',
            new_name='transaction_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
